### ISSUE TITLE
lint_mode background doesn't work

### ISSUE THREAD

**Issue by KingLoui** [SublimeLinter/SublimeLinter-cppcheck#10]
I'm using SublimeText on OS X El Capitan and installed cppcheck via homebrew.
When saving a file the linter works just fine but it seems he won't do anything on the fly when I'm typing.
I checked the settings for lint_mode and it is set to background, with php the background mode works just fine.

If you need any further information please let me know!

Thanks!

**Comment by NotSqrt** [comment]
It's expected (but not explicitly documented ..) : we use the file-only mode : http://www.sublimelinter.com/en/latest/linter_attributes.html#file-only-linters

As far as I know, cppcheck can't lint by reading from stdin, and really wants a file in the proper folder, otherwise there are many errors about relative headers not found, which means we can't use a temp file in another folder.

**Comment by KingLoui** [comment]
too bad!
Thanks nonetheless :)
