### ISSUE TITLE
Ignore errors on included headers

### ISSUE THREAD

**Issue by NotSqrt** [SublimeLinter/SublimeLinter-cppcheck#3]
cf https://groups.google.com/forum/#!topic/sublimelinter/QiGG4BVhg9I

**Comment by eaufavor** [comment]
Same thing happens for me . Cppcheck outputs the messages belongs to the current file as well ass some messages belong to the files it includes. I have a cpp file and a header file. SublimeLinter marks the errors  and warnings of header file on my cpp file. If my cpp file is shorter than my header file, the linter plugin just crashes because the line numbers are out of range.

**Comment by bjarkef** [comment]
I am seeing the exact same problem. This is kind of a deal breaker, as the current file is polluted with lint errors from other files. Should be a simple fix to ignore all lines with lint errors related to other files.

**Comment by NotSqrt** [comment]
I'm not working on C++ projects at the moment, so I haven't seen it.
Can you propose a fix ?

**Comment by ilearnio** [comment]
I have the same issue with `.hpp` header files. I wonder if it should maybe skip header files?

Example code:

```c++
typedef struct scope {
  int type;
} scope;
```

Gives me:

```
  $ /usr/local/bin/cppcheck --template=gcc --inline-suppr --quiet --enable=style /Users/Admin/Code/test/types.hpp

SublimeLinter: #701 SublimeLinter.sublime-package:790: cppcheck output:
    /Users/Admin/Code/test/types.hpp:2: style: struct member 'scope::type' is never used.
```

**Comment by kaste** [comment]
I may just use `excludes` here http://sublimelinter.readthedocs.io/en/stable/linter_settings.html#excludes

**Comment by ilearnio** [comment]
It worked, thanks!
