### ISSUE TITLE
Is this the correct settings format?

### ISSUE THREAD

**Issue by JohannesMP** [SublimeLinter/SublimeLinter-cppcheck#9]
As someone that hasn't used SublimeLinter before I want to check that I'm adding the settings in the right palce.

The readme points to the standard SublimeLinter documentation which isn't very clear on where settings are put. It says in one part "Each linter plugin is responsible for providing its own settings" (which to me would imply that each plugin is in charge of maintaining its own settings file), but their default settings file shows a "linters" section (which _isn't_ included in the default settings file that it installs with.

In any case, would this be the correct way to add cppcheck and have it work with a project being compiled with `-std=c++14`? https://gist.github.com/JohannesMP/95502c2f85d5ded0a8f3c42be8963b3b#file-sublimelinter-sublime-settings-L9-L13

**Comment by NotSqrt** [comment]
The readme might not be very clear, all linters have the same since we use the same template from SublimeLinter itself.

In your "SublimeLinter > Open user settings", there should be a new automatic section in the "linters" list for each linter that you install. if that's not the case, something is broken !

Now for the ``std`` setting, as mentionned in the readme, yes, ``"std": ["c++14"]`` should be the correct format (the readme shows ``["c89", "c99"]``), but I don't know which standards are supported by ``cppcheck`` !

**Comment by NotSqrt** [comment]
On my version, the choices are:
* posix: POSIX compatible code
* c89: C code is C89 compatible
* c99: C code is C99 compatible
* c11: C code is C11 compatible (default)
* c++03: C++ code is C++03 compatible
* c++11: C++ code is C++11 compatible (default)
